const translations: { [key: string]: string } = {
  "hello": "ہیلو",
  "world": "دنیا",
  "name": "نام",
  "friend": "دوست",
  "love": "محبت",
  "food": "کھانا",
  "water": "پانی",
  "book": "کتاب",
  "school": "سکول",
  "teacher": "استاد",
  "student": "طالب علم",
  "father": "والد",
  "mother": "والدہ",
  "brother": "بھائی",
  "sister": "بہن",
  "day": "دن",
  "night": "رات",
  "sun": "سورج",
  "moon": "چاند",
  "star": "ستارہ",
  "sky": "آسمان",
  "earth": "زمین",
  "air": "ہوا",
  "fire": "آگ",
  "light": "روشنی",
  "dark": "اندھیرا",
  "man": "آدمی",
  "woman": "عورت",
  "child": "بچہ",
  "baby": "نوزائیدہ",
  "home": "گھر",
  "house": "مکان",
  "car": "گاڑی",
  "road": "سڑک",
  "city": "شہر",
  "village": "گاؤں",
  "country": "ملک",
  "language": "زبان",
  "word": "لفظ",
  "sentence": "جملہ",
  "question": "سوال",
  "answer": "جواب",
  "yes": "ہاں",
  "no": "نہیں",
  "please": "براہ کرم",
  "thank you": "شکریہ",
  "sorry": "معاف کیجیے",
  "good": "اچھا",
  "bad": "برا",
  "happy": "خوش",
  "sad": "اداس",
  "fast": "تیز",
  "slow": "آہستہ",
  "hot": "گرم",
  "cold": "ٹھنڈا",
  "big": "بڑا",
  "small": "چھوٹا",
  "tall": "لمبا",
  "short": "چھوٹا",
  "old": "پرانا",
  "new": "نیا",
  "clean": "صاف",
  "dirty": "گندا",
  "strong": "مضبوط",
  "weak": "کمزور",
  "rich": "امیر",
  "poor": "غریب",
  "easy": "آسان",
  "hard": "مشکل",
  "beautiful": "خوبصورت",
  "ugly": "بدصورت",
  "open": "کھولنا",
  "close": "بند کرنا",
  "come": "آنا",
  "go": "جانا",
  "run": "دوڑنا",
  "walk": "چلنا",
  "sit": "بیٹھنا",
  "stand": "کھڑا ہونا",
  "sleep": "سونا",
  "wake": "جاگنا",
  "eat": "کھانا",
  "drink": "پینا",
  "see": "دیکھنا",
  "hear": "سننا",
  "speak": "بولنا",
  "read": "پڑھنا",
  "write": "لکھنا",
  "play": "کھیلنا",
  "work": "کام کرنا",
  "study": "مطالعہ کرنا",
  "buy": "خریدنا",
  "sell": "بیچنا",
  "help": "مدد کرنا",
  "wait": "انتظار کرنا",
  "drive": "چلانا",
  "think": "سوچنا",
  "understand": "سمجھنا",
  "remember": "یاد رکھنا",
  "forget": "بھولنا", 
  "router": "راؤٹر",
  "server": "سرور",
  "components": "اجزاء",
  "ui": "یوزر انٹرفیس",
  "theming": "تھیم بندی",
  "styling": "سجاوٹ",
  "accessibility": "رسائی",
  "testing": "جانچ",
  "review": "جائزہ",
  "demo": "ڈیمو",
  "quote": "اقتباس",
  "generator": "جنریٹر",
  "intro": "تعارف",
  "webhooks": "ویب ہکس",
  "agents": "ایجنٹس",
  "integration": "انضمام",
  "crud": "کریئیٹ، ریڈ، اپڈیٹ، ڈیلیٹ",
  "ci/cd": "مسلسل انضمام / مسلسل تعیناتی",
  "actions": "اعمال",
  "due": "آخری تاریخ",
  "sprint": "تیز کام",
  "wireframes": "وائر فریمز",
  "backend": "بیک اینڈ",
  "db": "ڈیٹا بیس",
  "milestone": "اہم مرحلہ",
  "pushed": "دھکیلا گیا / اپ لوڈ کیا گیا",
  "frontend": "فرنٹ اینڈ",
  "logic": "منطق",
  "polish": "چمکانا / بہتر بنانا",
  "responsiveness": "جوابی صلاحیت",
  "bug-fixing": "خرابی دور کرنا",
  "tweaks": "تبدیلیاں",
  "public": "عوامی",
  "live": "براہ راست",
  "qa": "کوالٹی اشورنس",
  "optimization": "بہتری",
  "docs": "دستاویزات",
  "walkthrough": "وضاحت",
  "final": "حتمی",
  "building": "تعمیر کرنا",
  "intelligent": "ذہین",
  "solutions": "حل",
  "transformation": "تبدیلی",
  "technology": "ٹیکنالوجی",
  "internet": "انٹرنیٹ",
  "SpaceX": "اسپیس ایکس",
  "planning": "منصوبہ بندی",
  "launch": "لانچ",
  "10th": "دسویں",
  "Starship": "اسٹارشپ",
  "test": "ٹیسٹ",
  "flight": "فلائٹ",
  "weeks": "ہفتوں",
  "according": "مطابق",
  "company": "کمپنی",
  "founder": "بانی",
  "CEO": "سی ای او",
  "Elon Musk": "ایلون مسک",
  "shared": "شیئر کیا",
  "update": "اپ ڈیٹ",
  "Monday": "پیر",
  "July": "جولائی",
  "August": "اگست",
  "next": "اگلا",
  "post": "بعد",
  "marking": "نشان زد",
  "fourth": "چوتھی",
  "year": "سال",
  "faced": "سامنا",
  "setbacks": "رکاوٹوں",
  "routine": "معمول",
  "tests": "ٹیسٹوں",
  "upper": "اوپری",
  "stage": "اسٹیج",
  "originally": "اصل میں",
  "fly": "اڑانے",
  "blew up": "پھٹ گیا",
  "ground": "زمینی",
  "Starbase": "اسٹاربیس",
  "June": "جون",
  "prepping": "تیار کر رہا تھا",
  "engine": "انجن",
  "check": "چیک",
  "digging": "جائزہ لینے",
  "team": "ٹیم",
  "traced": "پتہ لگایا",
  "problem": "مسئلہ",
  "failed": "ناکام",
  "pressurized": "دباؤ والی",
  "nitrogen": "نائٹروجن",
  "tank": "ٹینک",
  "nosecone": "ناک کون",
  "switching gears": "گئر تبدیل",
  "different": "مختلف",
  "Ship": "جہاز",
  "place": "جگہ",
  "booster": "بوسٹر",
  "lost": "ضائع",
  "minutes": "منٹ",
  "contact": "رابطہ",
  "January": "جنوری",
  "catch": "پکڑنے",
  "tower": "ٹاور",
  "chopstick": "چاپ اسٹک",
  "arms": "بازوؤں",
  "mission": "مشن",
  "exploded": "پھٹ گیا",
  "mid-ascent": "چڑھتے ہوئے",
  "March": "مارچ",
  "reusability": "دوبارہ استعمال کی صلاحیت",
  "system": "نظام",
  "reliability": "وشوسنییتا",
  "critical": "ضروری",
  "Mars": "مریخ",
  "resupplying": "دوبارہ سپلائی",
  "stations": "اسٹیشنوں",
  "astronauts": "خلابازوں",
  "Moon": "چاند",
  "cargo": "سامان",
  "rocket": "راکٹ",
  "Raptor": "ریپٹر",
  "engines": "انجنوں",
  "liquid": "مائع",
  "methane": "میتھین",
  "oxygen": "آکسیجن",
  "reusable": "دوبارہ قابل استعمال",
  "development": "ترقی",
  "facility": "سہولت",
  "Boca Chica": "بوکا چیکا",
  "Texas": "ٹیکساس",
  "FAA": "ایف اے اے",
  "approval": "منظوری",
  "affiliate links": "افیلی ایٹ لنکس",
  "sustain": "اپنا خیال رکھنے",
  "connection requests": "کنکشن درخواستیں",
  "IP address": "IP ایڈریس",
  "target": "ہدف بنائی گئی",
  "web page": "ویب پیج",
  "trigger": "ٹرگر",
  "sandboxes": "سینڈ باکسز",
  "practice": "مشق",
  "web scraping": "ویب سکریپنگ",
  "skills": "مہارتیں",
  "automated process": "خودکار عمل",
  "extracting": "نکالنے",
  "data": "ڈیٹا",
  "web scraper": "ویب سکریپر",
  "HTML code": "HTML کوڈ",
  "parses": "پارس کرتا ہے",
  "structured": "ساختہ",
  "tools": "اوزار",
  "categories": "زمروں",
  "custom-built": "اپنی مرضی کے مطابق بنائے گئے",
  "ready-made": "تیار شدہ",
  "APIs": "APIs",
  "programming languages": "پروگرامنگ زبانیں",
  "libraries": "لائبریریز",
  "frameworks": "فریم ورکس",
  "functionality": "فعالیت",
  "user-friendly": "صارف دوست",
  "interface": "انٹرفیس",
  "minimal": "کم سے کم",
  "middle ground": "درمیانی راستہ",
  "building from scratch": "صفر سے بنانے",
  "basic knowledge": "بنیادی علم",
  "pricing changes": "قیمتوں میں تبدیلی",
  "market trends": "مارکیٹ کے رجحانات",
  "competitor activity": "مقابلہ کرنے والے کی سرگرمی",
  "legal": "قانونی",
  "bot-like activities": "بوٹ جیسی سرگرمیاں",
  "burden": "بوجھ",
  "web servers": "ویب سرورز",
  "robots.txt": "robots.txt",
  "block": "بلاک",
  "proxies": "پراکسیز",
  "bypass": "بائی پاس",
  "IP blocks": "IP بلاکس",
  "throttled": "تھروٹل",
  "middleman": "درمیانی آدمی",
  "masking": "چھپاتا ہے",
  "location": "مقام",
  "geo-restricted": "جغرافیائی پابندی والے",
  "targeted destination": "ہدف شدہ مقام",
  "high-volume": "بڑی مقدار",
  "data collection": "ڈیٹا کے جمع کرنے",
  "endpoints": "اینڈ پوائنٹس",
  "log in": "لاگ ان",
  "JavaScript-generated content": "JavaScript سے بننے والا مواد",
  "lazy loading": "لیزی لوڈنگ",
  "delayed rendering": "تاخیر سے رینڈرنگ",
  "headless browser": "ہیڈ لیس براؤزر",
  "dedicated environment": "مخصوص ماحول",
  "refine": "بہتر بنانے",
  "e-commerce platform": "ای کامرس پلیٹ فارم",
  "dynamic content": "متحرک مواد",
  "mimicking": "نقل کرتے ہوئے",
  "complexities": "پیچیدگیوں",
  "product listings": "مصنوعات کی لسٹنگ",
  "pagination": "پیجینیشن",
  "search queries": "تلاش کے سوالات",
  "structured data": "ساختہ ڈیٹا",
  "JSON format": "JSON فارمیٹ",
  "financial records": "مالیاتی ریکارڈز",
  "stock market": "اسٹاک مارکیٹ",
  "tables": "ٹیبلز",
  "charts": "چارٹس",
  "financial statement": "مالیاتی بیان",
  "number crunching": "نمبر کرنچنگ",
  "CSV file": "CSV فائل",
  "Excel Spreadsheet": "ایکسل اسپریڈ شیٹ",
  "identifiers": "شناخت کنندگان",
  "properties": "خصوصیات",
  "content unit": "مواد کے یونٹ",
  "redesign": "ری ڈیزائن",
  "let": "دیتے ہیں",
  "coming": "سے",
  "offer": "پیش کرتی ہیں",
  "show": "دکھائے گا",
  "pick up": "سیکھ",
  "copying": "کاپی کرنے",
  "downloads": "ڈاؤن لوڈ کرتا ہے",
  "makes": "بناتا ہے",
  "fall": "آتے ہیں",
  "serve": "پورے کرتے ہیں",
  "provide": "فراہم کرتے ہیں",
  "achieve": "حاصل کرنے",
  "extract": "نکالنے",
  "allowing": "اجازت دیتا ہے",
  "require": "ضرورت ہوتی ہے",
  "get": "حاصل کر سکتا ہے",
  "allow": "اجازت دیتی ہے",
  "plan": "منصوبہ بنا رہے ہیں",
  "scrape": "سکریپ",
  "available": "دستیاب",
  "used": "استعمال ہوتی ہیں",
  "make": "کرتے ہیں",
  "teach": "سکھا سکتا ہے",
  "complete": "مکمل کرنے",
  "try out": "آزمانا",
  "designed": "ڈیزائن کیا گیا",
  "featuring": "کی خصوصیت",
  "allows": "اجازت دیتا ہے",
  "navigate": "نیویگیٹ کر سکتے ہیں",
  "manage": "منظم کر سکتے ہیں",
  "handle": "ہینڈل کر سکتے ہیں",
  "provides": "فراہم کرتا ہے",
  "delivers": "فراہم کرتا ہے",
  "start": "شروع کرنے",
  "practicing": "مشق",
  "pull": "نکال سکتے ہیں",
  "recommend": "سفارش کرتا ہوں",
  "calculate": "حساب لگایا جا سکے",
  "deal with": "سے نمٹا جائے",
  "hone": "بہتر بنا",
  "goes too fast": "بہت تیز چلتا ہے",
  "tread carefully": "محتاط رہیں",
  "suggest": "مشورہ دوں گا"
};



export function translateText(text: string): string {
  return text
    .split(' ')
    .map(word => translations[word] || word)
    .join(' ');
}
